# -*- coding: utf-8 -*-
# ENG VERSION

AAA_SITE_PARAMS = { 'site_name':u'Guide in Rome',
      'site_footer':'© 2011 Guide in Rome, gidinrome.com. All rights reserved.',
      'page_title':'Individual guide in Rome. gidinrome.com',
      'page_keywords':"Individual guide in Rome. gidinrome.com",
      'page_description':u"Офицальный сайт Ольги Новиковой - гида-переводчика в Риме",
      'owner_phone':"+39 3336631315",
      'owner_phone_title':"Phone",
      'owner_skype':"olga.novikova22",
      'owner_email':"oan_75@mail.ru",
      'owner_name':"Olga",
      'owner_status':"Individual guide in Rome",
      'owner_maintitle':"Excursions in Rome",
      'owner_maintext':"We are offering you interesting sightseeing tours in Rome and its suburbs with me - English - speaking lisenced tour guide in Rome and Lazio region. You can visit archeological sites, art galleries, cathedrals, sculpture museums and many other places. As Rome is located on west coast of central Italy (about 20 kilometres away from the place where Tiber river falls into Tyrrhenian sea) you will be able to have nice visits also to the nearest pittoresque seacoast. In the tour list you will find classical and themed individual tours in Eternal city.",
      'owner_friends_title':"Friends",
      'url_name_fotos':"Foto",
      'url_name_main':"Main",
      'url_name_recomendations':"Recomendations",
      'url_name_contacts':"Contacts",
      'url_name_notes':"Notes",
      'url_name_info':"Information",
      'url_name_transfer':"Transfer",
      'url_name_shops':"Shops",
      'url_name_transport':"Transport",
      'url_name_italy':"Other Italy cities",
      'url_name_translate':"Translate",
      'url_name_license':"License",
      'url_name_hotels':"Hotels",
      'url_name_flights':"Flights",
      'url_name_restaurants':"Restaurants",
	    }

