# -*- coding: utf-8 -*-
# ENG VERSION

LANGUAGE_CODE = 'en-US'
SITE_ID = 2

AAA_SITE_PARAMS = {
      """
      'site_name':u'Guide in Rome',
      'site_footer':u'© 2012 Guide in Rome, gidinrome.com. All rights reserved.',
      'page_title':u'Individual guide in Rome. gidinrome.com',
      'page_keywords':u"Individual guide in Rome. gidinrome.com",
      'page_description':u"Olga Novikova Official Site - guide in Rome",
      'owner_phone':u"+39 3336631315",
      'owner_phone_title':u"Phone",
      'owner_skype':u"olga.gidinrome",
      'owner_email':u"olga@rim-gid.com",
      'owner_name':u"Olga",
      'owner_status':u"Individual guide in Rome",
      'owner_maintitle':u"Excursions in Rome",
      'owner_maintext':u"We are offering you interesting sightseeing tours in Rome and its suburbs with me - English - speaking lisenced tour guide in Rome and Lazio region. You can visit archeological sites, art galleries, cathedrals, sculpture museums and many other places. As Rome is located on west coast of central Italy (about 20 kilometres away from the place where Tiber river falls into Tyrrhenian sea) you will be able to have nice visits also to the nearest pittoresque seacoast. In the tour list you will find classical and themed individual tours in Eternal city.",
      'owner_friends_title':u"Friends",
      'url_name_fotos':u"Foto",
      'url_name_main':u"Main",
      'url_name_reccomendations':u"Reccomendations",
      'url_name_contacts':u"Contacts",
      'url_name_notes':u"Notes",
      'content_name_notes':u"News",
      'content_name_notes_no':u"No any news yet",
      'url_name_info':u"Information",
      'content_name_info':u"Information",
      'content_name_info_no':u"No any posts yet",
      'url_name_transfer':u"Transfer",
      'content_name_transfer':u"Transfer",
      'url_name_shops':u"Shops",
      'content_name_shops':u"Shops",
      'content_name_shops_no':u"No any posts yet",
      'url_name_transport':u"Transport",
      'content_name_transport':u"Transport",
      'content_name_transport_no':u"No any posts yet",
      'url_name_italy':u"Other Italy cities",
      'url_name_translate':u"Translate",
      'url_name_license':u"License",
      'url_name_hotels':u"Hotels",
      'content_name_hotels':u"Hotels",
      'content_name_hotels_no':u"No any posts yet",
      'url_name_flights':u"Flights",
      'content_name_flights':u"Flights",
      'content_name_flights_no':u"No any posts yet",
      'url_name_restaurants':u"Restaurants",
      'content_name_restaurants':u"Restaurants",
      'content_name_restaurants_no':u"No any posts yet",
      'msg_thx':u"Thank you! I`ll give you answer in a few days",
      'msg_error':u"Error. Maybe it`s site problem",
      'msg_error_repeat':u"If error repeats, use e-mail: olga@rim-gid.com",
      'msg_error_contacts':u"Or contact with me other way. My contacts are on the page: http://gidinrome.com/contacts",
      'request_title':u"Request",
      'request_msg_error':u"Please, correct all errors",
      'form_label_name':u"Your name:",
      'form_input_name':u"Write your name...",
      'form_label_date':u"Excursion date:",
      'form_input_date':u"Write your date...",
      'form_label_email':u"E-mail:",
      'form_input_email':u"Write your e-mail...",
      'form_label_comments':u"Comments:",
      'form_input_comments':u"Write your wishes about tour...",
      'request_button_text':u"Send",
      'to_main_text':u"To main page",
      'site_version':u"eng",
      """
      'su_pass':"ceTNil",#"gahaciicpi",
      'pointed_su_pass':"ceTNil",#"udtufugeve",
      'pointed_address':"10.10.10.59",#"141.8.193.148",
	    }

