#! /bin/sh
### BEGIN INIT INFO
# Provides:          celeryb
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Python tasks scheduler
# Description:       Debian init script for the celery python tasks
#                    scheduler
### END INIT INFO
#
# Author:	Andrey Andreev <aa.veter@gmail.com>
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=$CONTROL_PATH/start_celery
PIDFILE=/var/run/celeryb.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting python tasks scheduler" "celery"
	start_daemon -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping python tasks scheduler" "celery"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON celeryb && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/celeryb {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
