# -*- coding: utf-8 -*-
# RUS VERSION

LANGUAGE_CODE = 'ru-RU'
SITE_ID = 1

AAA_SITE_PARAMS = {
      """
      'site_name':u'Гид по Риму',
      'site_footer':u'© 2012 Гид по Риму, rim-gid.com. Все права защищены. Использование информации без ссылки на сайт запрещено.',
      'page_title':u'Русскоязычный индивидуальный гид по Риму и Италии. Экскурсии на русском языке в Риме в Италии русскоговорящий гид. rim-gid.com',
      'page_keywords':u"Русскоязычный индивидуальный гид по Риму и Италии. Экскурсии на русском языке в Риме в Италии русскоговорящий гид. rim-gid.com",
      'page_description':u"Офицальный сайт Ольги Новиковой - гида-переводчика в Риме",
      'owner_phone':"+39 3336631315",
      'owner_phone_title':u"Телефон",
      'owner_skype':"olga.gidinrome",
      'owner_email':"olga@rim-gid.com",
      'owner_name':u"Ольга",
      'owner_status':u"Русскоговорящий лицензированный гид-переводчик по Риму и региону Лацио",
      'owner_maintitle':u"Экскурсии в Риме",
      'owner_maintext':u"Предлагаю Вам увлекательные экскурсии по Риму и его пригородам со мной - русскоговорящим лицензированным гидом-переводчиком по Риму и региону Лацио. Вы сможете посетить археологические музеи, соборы, картинные галереи, музеи скульптуры и многое другое. Так как Рим расположен близ западного побережья Центральной Италии (примерно в 20 километрах от места впадения реки Тибр в Тирренское море), мы также сможем совершить интересные поездки на живописные морские курорты.",
      'owner_friends_title':u"Друзья",
      'url_name_fotos':u"Фото",
      'url_name_main':u"Главная",
      'url_name_reccomendations':u"Отзывы",
      'url_name_contacts':u"Контакты",
      'url_name_notes':u"Новости",
      'content_name_notes':"Новости",
      'content_name_notes_no':"Еще нет ни одной новости",
      'url_name_info':u"Информация",
      'content_name_info':"Информация",
      'content_name_info_no':"Пока нет заметок",
      'url_name_transfer':u"Трансфер",
      'content_name_transfer':"Трансфер",
      'url_name_shops':u"Магазины",
      'content_name_shops':"Магазины",
      'content_name_shops_no':"Пока нет заметок о магазинах",
      'url_name_transport':u"Транспорт",
      'content_name_transport':"Транспорт",
      'content_name_transport_no':"Пока нет заметок о транспорте",
      'url_name_italy':u"Экскурсии по другим городам Италии",
      'url_name_translate':u"Услуги перевода",
      'url_name_license':u"Лицензия",
      'url_name_hotels':u"Отели",
      'content_name_hotels':"Отели",
      'content_name_hotels_no':"Пока нет заметок об отелях",
      'url_name_flights':u"Авиаперелеты",
      'content_name_flights':"Авиаперелеты",
      'content_name_flights_no':"Пока нет заметок об авиа",
      'url_name_restaurants':u"Рестораны",
      'content_name_restaurants':u"Рестораны",
      'content_name_restaurants_no':u"Пока нет заметок о ресторанах",
      'msg_thx':u"Спасибо за заявку! Я отвечу Вам в ближайшее время (в течение нескольких дней)",
      'msg_error':u"Ошибка! Возможно, это проблемы с сайтом",
      'msg_error_repeat':u"Если проблема повторяется, отправьте, пожалуйста, заявку вручную на e-mail: olga@rim-gid.com",
      'msg_error_contacts':u"Или свяжитесь со мной любым удобным для Вас способом. Мои контакты указаны на странице: gid-rim.com/contacts",
      'request_title':u"Заявка",
      'request_msg_error':u"Исправьте, пожалуйста, все ошибки",
      'form_label_name':u"Ваше имя:",
      'form_input_name':u"Введите Ваше имя...",
      'form_label_date':u"Предпочтительная дата экскурсии:",
      'form_input_date':u"Введите желаемую дату...",
      'form_label_email':u"Ваш e-mail:",
      'form_input_email':u"Адрес почты...",
      'form_label_comments':u"Комментарий к заказу:",
      'form_input_comments':u"Напишите дополнительные пожелания...",
      'request_button_text':u"Заказать",
      'to_main_text':u"На главную",
      'site_version':"ru",
      """
      'su_pass':"ceTNil",#"udtufugeve",
      'pointed_su_pass':"ceTNil",#"gahaciicpi",
      'pointed_address':"10.10.10.7",#"141.8.193.142",
	    }

