# -*- coding: utf-8 -*-
# RUS VERSION

AAA_SITE_PARAMS = { 'site_name':u'Гид по Риму',
      'site_footer':u'© 2011 Гид по Риму, rim-gid.com. Все права защищены. Использование информации без ссылки на сайт запрещено.',
      'page_title':u'Русскоязычный индивидуальный гид по Риму и Италии. Экскурсии на русском языке в Риме в Италии русскоговорящий гид. rim-gid.com',
      'page_keywords':u"Русскоязычный индивидуальный гид по Риму и Италии. Экскурсии на русском языке в Риме в Италии русскоговорящий гид. rim-gid.com",
      'page_description':u"Офицальный сайт Ольги Новиковой - гида-переводчика в Риме",
      'owner_phone':"+39 3336631315",
      'owner_phone_title':u"Телефон",
      'owner_skype':"olga.gidinrome",
      'owner_email':"olga@rim-gid.com",
      'owner_name':u"Ольга",
      'owner_status':u"Русскоговорящий лицензированный гид-переводчик по Риму и региону Лацио",
      'owner_maintitle':u"Экскурсии в Риме",
      'owner_maintext':u"Предлагаю Вам увлекательные экскурсии по Риму и его пригородам со мной - русскоговорящим лицензированным гидом-переводчиком по Риму и региону Лацио. Вы сможете посетить археологические музеи, соборы, картинные галереи, музеи скульптуры и многое другое. Так как Рим расположен близ западного побережья Центральной Италии (примерно в 20 километрах от места впадения реки Тибр в Тирренское море), мы также сможем совершить интересные поездки на живописные морские курорты.",
      'owner_friends_title':u"Друзья",
      'url_name_fotos':u"Фото",
      'url_name_main':u"Главная",
      'url_name_reccomendations':u"Отзывы",
      'url_name_contacts':u"Контакты",
      'url_name_notes':u"Новости",
      'content_name_notes':"Новости",
      'url_name_info':u"Информация",
      'content_name_notes':"Информация",
      'url_name_transfer':u"Трансфер",
      'content_name_notes':"Трансфер",
      'url_name_shops':u"Магазины",
      'content_name_notes':"Магазины",
      'url_name_transport':u"Транспорт",
      'content_name_notes':"Транспорт",
      'url_name_italy':u"Экскурсии по другим городам Италии",
      'url_name_translate':u"Услуги перевода",
      'url_name_license':u"Лицензия",
      'url_name_hotels':u"Отели",
      'content_name_notes':"Отели",
      'url_name_flights':u"Авиаперелеты",
      'content_name_notes':"Авиаперелеты",
      'url_name_restaurants':u"Рестораны",
      'content_name_notes':"Рестораны",
      'site_version':"ru",
	    }

